apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: k8s-redis-service
  annotations:
    description: "Application secrets"
type: Opaque
data:
  # 敏感信息需要进行base64编码
  # password: echo -n "123456" | base64
  redis-password: MTIzNDU2